server:
  port: 8080
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/employee_management_system?useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
